[package]
name = "pont-client"
version = "0.1.0"
authors = ["Matt Keeter"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pont-common = { path = "../pont-common" }
serde_json = "*"
wasm-bindgen = "^0.2"

[dependencies.web-sys]
version = "*"
features = [
  'Document',
  'Element',
  'ErrorEvent',
  'HtmlElement',
  'MessageEvent',
  'SvgElement',
  'SvgCircleElement',
  'Node',
  "WebSocket",
  'Window',
]
